# [Choice] Ubuntu version: bionic, focal
ARG VARIANT=latest
FROM ghcr.io/mi-skam/nix:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>


